[module]
  [module.hugoVersion]
    extended = true
    min = "0.110.0"
    max = ""
  [[module.imports]]
    path = "github.com/airbnb/lottie-web"
  [[module.imports.mounts]]
    source = "build/player/lottie_light.js"
    target = "assets/js/modules/lottie/lottie_light.js"
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'data'
    target = 'data'
  [[module.imports]]
    path = "github.com/gethinode/mod-utils/v2"
