baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Test site for mod-lottie'

[module]
  replacements = 'github.com/gethinode/mod-lottie -> ../..'
  [[module.imports]]
    path = "github.com/gethinode/mod-lottie"
  [[module.imports.mounts]]
    source = "assets"
    target = "assets"
  [[module.imports.mounts]]
    source = "data"
    target = "data"
  [[module.imports.mounts]]
    source = "dist"
    target = "static"
  [[module.imports.mounts]]
    source = "layouts"
    target = "layouts"